"""
=============================================================
  DRIVE WORKER — Stateless Rendering Engine
  Runs on Google Colab or Kaggle. Processes one scene at a time.
=============================================================

This script is the workhorse of the distributed pipeline.
It runs in a loop:
  1. Claims the next unclaimed scene from Google Drive
  2. Generates visuals via ComfyUI (running locally on the GPU)
  3. Merges audio + video with FFmpeg
  4. Writes output atomically (.tmp → .mp4) to Drive
  5. Repeats until no scenes remain

The worker is FULLY STATELESS:
  - It can be killed at any time without data loss
  - Multiple workers can run simultaneously (different Colab/Kaggle sessions)
  - A new worker automatically picks up where a crashed one left off

Usage (called from a Colab/Kaggle notebook cell):
  !python drive_worker.py --drive-path /content/drive/MyDrive/AnimeFactory
"""

import argparse
import json
import os
import random
import subprocess
import sys
import time
import urllib.request
import uuid

# Add the project to Python path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from drive_state import DriveState


# ===========================================================
# CONFIGURATION
# ===========================================================

COMFYUI_URL = "http://127.0.0.1:8188"  # Local ComfyUI on the same GPU machine

# Manhwa style for all generations
STYLE_PREFIX = "manhwa style, webtoon art, sharp linework, vibrant colors, ultra detailed, masterpiece, best quality, "
NEGATIVE_PROMPT = "low quality, worst quality, blurry, bad anatomy, bad proportions, deformed, ugly, 3d render, photorealistic, watermark, text, signature, extra limbs"

# Voice map not needed here — TTS is pre-generated by drive_uploader.py


# ===========================================================
# COMFYUI API HELPERS
# ===========================================================

def api_post(url, data):
    """Send a JSON POST request to ComfyUI."""
    body = json.dumps(data).encode("utf-8")
    req = urllib.request.Request(url, data=body, headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=300) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        print(f"  [ERROR] API call to {url} failed: {e}")
        return None


def api_get(url):
    """Send a GET request to ComfyUI."""
    try:
        with urllib.request.urlopen(url, timeout=30) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        return None


def wait_for_comfyui_ready():
    """Wait until ComfyUI is responding on its API port."""
    print("[WORKER] Waiting for ComfyUI to be ready...")
    for i in range(60):  # Wait up to 5 minutes
        result = api_get(f"{COMFYUI_URL}/system_stats")
        if result:
            print("[WORKER] ComfyUI is ready!")
            return True
        time.sleep(5)
    print("[WORKER] ERROR: ComfyUI did not start in time!")
    return False


# ===========================================================
# IMAGE GENERATION (AnythingXL)
# ===========================================================

def generate_image(prompt, scene_id, comfyui_output_dir):
    """Generate a manhwa-style image via ComfyUI AnythingXL."""
    full_prompt = STYLE_PREFIX + prompt
    unique_prefix = scene_id
    
    workflow = {
        "1": {
            "inputs": {"ckpt_name": "AnythingXL_xl.safetensors"},
            "class_type": "CheckpointLoaderSimple"
        },
        "2": {
            "inputs": {"text": full_prompt, "clip": ["1", 1]},
            "class_type": "CLIPTextEncode"
        },
        "3": {
            "inputs": {"text": NEGATIVE_PROMPT, "clip": ["1", 1]},
            "class_type": "CLIPTextEncode"
        },
        "4": {
            "inputs": {"width": 1216, "height": 832, "batch_size": 1},
            "class_type": "EmptyLatentImage"
        },
        "5": {
            "inputs": {
                "seed": random.randint(1, 2**32),
                "steps": 25, "cfg": 7.0,
                "sampler_name": "euler", "scheduler": "karras",
                "denoise": 1.0,
                "model": ["1", 0], "positive": ["2", 0],
                "negative": ["3", 0], "latent_image": ["4", 0]
            },
            "class_type": "KSampler"
        },
        "6": {
            "inputs": {"samples": ["5", 0], "vae": ["1", 2]},
            "class_type": "VAEDecode"
        },
        "7": {
            "inputs": {"filename_prefix": unique_prefix, "images": ["6", 0]},
            "class_type": "SaveImage"
        }
    }
    
    print(f"  [IMG] Generating image for {scene_id}...")
    result = api_post(f"{COMFYUI_URL}/prompt", {"prompt": workflow})
    
    if not result or "prompt_id" not in result:
        print(f"  [IMG] FAILED to queue {scene_id}")
        return None
    
    return wait_for_output(result["prompt_id"], unique_prefix, comfyui_output_dir)


# ===========================================================
# VIDEO GENERATION (Wan2.1)
# ===========================================================

def generate_video(prompt, scene_id, comfyui_output_dir, part=1, fps=16):
    """Generate a video clip via ComfyUI Wan2.1."""
    full_prompt = STYLE_PREFIX + prompt
    unique_prefix = f"{scene_id}_p{part}"
    
    wan_negative = "low quality, worst quality, blurry, static, distorted, 3d render, photorealistic, ugly"
    
    workflow = {
        "37": {
            "inputs": {
                "unet_name": "wan2.1_t2v_1.3B_fp16.safetensors",
                "weight_dtype": "default"
            },
            "class_type": "UNETLoader"
        },
        "38": {
            "inputs": {
                "clip_name": "umt5_xxl_fp8_e4m3fn_scaled.safetensors",
                "type": "wan",
                "device": "default"
            },
            "class_type": "CLIPLoader"
        },
        "39": {
            "inputs": {"vae_name": "wan_2.1_vae.safetensors"},
            "class_type": "VAELoader"
        },
        "48": {
            "inputs": {"model": ["37", 0], "shift": 8},
            "class_type": "ModelSamplingSD3"
        },
        "6": {
            "inputs": {"text": full_prompt, "clip": ["38", 0]},
            "class_type": "CLIPTextEncode"
        },
        "7": {
            "inputs": {"text": wan_negative, "clip": ["38", 0]},
            "class_type": "CLIPTextEncode"
        },
        "40": {
            "inputs": {"width": 832, "height": 480, "length": 81, "batch_size": 1},
            "class_type": "EmptyHunyuanLatentVideo"
        },
        "3": {
            "inputs": {
                "seed": random.randint(1, 2**32),
                "steps": 30, "cfg": 6.0,
                "sampler_name": "uni_pc", "scheduler": "simple",
                "denoise": 1.0,
                "model": ["48", 0], "positive": ["6", 0],
                "negative": ["7", 0], "latent_image": ["40", 0]
            },
            "class_type": "KSampler"
        },
        "8": {
            "inputs": {"samples": ["3", 0], "vae": ["39", 0]},
            "class_type": "VAEDecode"
        },
        "28": {
            "inputs": {
                "filename_prefix": unique_prefix,
                "codec": "vp9", "fps": fps, "crf": 32,
                "images": ["8", 0]
            },
            "class_type": "SaveWEBM"
        }
    }
    
    print(f"  [VIDEO] Generating {scene_id} part {part} @ {fps} FPS...")
    result = api_post(f"{COMFYUI_URL}/prompt", {"prompt": workflow})
    
    if not result or "prompt_id" not in result:
        print(f"  [VIDEO] FAILED to queue {scene_id} part {part}")
        return None
    
    return wait_for_output(result["prompt_id"], unique_prefix, comfyui_output_dir)


def wait_for_output(prompt_id, prefix, comfyui_output_dir):
    """Poll ComfyUI until generation is done, then find the output file."""
    max_wait = 900  # 15 minutes
    elapsed = 0
    
    while elapsed < max_wait:
        time.sleep(5)
        elapsed += 5
        
        history = api_get(f"{COMFYUI_URL}/history/{prompt_id}")
        if history and prompt_id in history:
            print(f"  [DONE] ComfyUI finished in {elapsed}s")
            break
    else:
        print(f"  [TIMEOUT] ComfyUI took too long for {prefix}")
        return None
    
    # Find output file
    matching = []
    for f in os.listdir(comfyui_output_dir):
        if f.startswith(prefix) and not f.endswith(".webp"):
            matching.append(os.path.join(comfyui_output_dir, f))
    
    if matching:
        matching.sort(key=os.path.getmtime, reverse=True)
        print(f"  [FOUND] {matching[0]}")
        return matching[0]
    
    print(f"  [ERROR] No output file found for {prefix}")
    return None


# ===========================================================
# SCENE PROCESSING (One scene at a time)
# ===========================================================

def process_scene(scene_info, state, comfyui_output_dir):
    """
    Process a single scene: generate visuals, merge with audio, save.
    
    Args:
        scene_info: Dict from DriveState.claim_next_scene()
        state: DriveState instance
        comfyui_output_dir: ComfyUI's output directory on this machine
    
    Returns:
        Path to the final .tmp output, or None on failure.
    """

    scene_id = scene_info["id"]
    scene_data = scene_info["data"]
    scene_type = scene_data.get("type", "image")
    
    # Resolve the correct prompt based on scene type for character and style consistency
    if scene_type == "video":
        visual_prompt = (
            scene_data.get("video_prompt") 
            or scene_data.get("visual_prompt") 
            or scene_data.get("image_prompt") 
            or scene_data.get("text") 
            or scene_data.get("story_text") 
            or ""
        )
    else:
        visual_prompt = (
            scene_data.get("image_prompt") 
            or scene_data.get("visual_prompt") 
            or scene_data.get("text") 
            or scene_data.get("story_text") 
            or ""
        )
    
    # Get pre-generated audio from Drive
    audio_path = os.path.join(state.tts_dir, f"{scene_id}.mp3")
    if not os.path.exists(audio_path):
        print(f"  [ERROR] Missing TTS audio: {audio_path}")
        return None
    
    # Generate visual(s)
    if scene_type == "video":
        visual_path = generate_video_scene(visual_prompt, scene_id, comfyui_output_dir)
    else:
        visual_path = generate_image(visual_prompt, scene_id, comfyui_output_dir)
    
    if not visual_path:
        return None
    
    # Merge audio + visual into scene video
    tmp_output = os.path.join(state.scenes_dir, f"{scene_id}.tmp")
    if merge_scene(visual_path, audio_path, tmp_output, scene_type == "image"):
        return tmp_output
    
    return None


def generate_video_scene(prompt, scene_id, comfyui_output_dir):
    """
    Generate dual-clip video scene (wide shot + close up).
    Concatenates both parts with FFmpeg.
    """
    # Dynamic FPS pacing
    rand_val = random.random()
    if rand_val < 0.50:
        fps = 24
    elif rand_val < 0.85:
        fps = 16
    else:
        fps = 8
    
    print(f"  [VIDEO] Dynamic pacing: {fps} FPS for {scene_id}")
    
    # Part 1: Wide shot
    path_1 = generate_video(prompt + ", wide shot, full body, environment visible",
                            scene_id, comfyui_output_dir, part=1, fps=fps)
    if not path_1:
        return None
    
    # Part 2: Close up
    path_2 = generate_video(prompt + ", dramatic close up shot, detailed face",
                            scene_id, comfyui_output_dir, part=2, fps=fps)
    if not path_2:
        return path_1  # Use just part 1 if part 2 fails
    
    # Concatenate both parts
    concat_path = os.path.join(comfyui_output_dir, f"{scene_id}_concat.webm")
    concat_txt = os.path.join(comfyui_output_dir, f"{scene_id}_concat.txt")
    
    with open(concat_txt, "w") as f:
        f.write(f"file '{os.path.abspath(path_1).replace(chr(92), '/')}'\n")
        f.write(f"file '{os.path.abspath(path_2).replace(chr(92), '/')}'\n")
    
    try:
        subprocess.run(
            ["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", concat_txt,
             "-c", "copy", concat_path],
            stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT, check=True
        )
        print(f"  [VIDEO] Concatenated {scene_id}: 2 clips merged")
        return concat_path
    except subprocess.CalledProcessError:
        print(f"  [ERROR] FFmpeg concat failed for {scene_id}")
        return path_1  # Fallback to just part 1


def merge_scene(visual_path, audio_path, output_path, is_image):
    """
    Merge visual + audio into a final scene video using FFmpeg.
    Uses simple scale+pad for maximum compatibility.
    """
    if is_image:
        # -loop 1 makes FFmpeg loop the single image for the duration of the audio
        command = [
            "ffmpeg", "-y",
            "-loop", "1", "-i", visual_path,
            "-i", audio_path,
            "-filter_complex",
                "[0:v]scale=1920:1080:force_original_aspect_ratio=decrease,"
                "pad=1920:1080:(ow-iw)/2:(oh-ih)/2:color=black,"
                "format=yuv420p[final]",
            "-map", "[final]", "-map", "1:a",
            "-c:v", "libx264", "-preset", "fast", "-tune", "stillimage",
            "-c:a", "aac", "-b:a", "192k",
            "-shortest", output_path
        ]
    else:
        command = [
            "ffmpeg", "-y",
            "-i", visual_path,
            "-i", audio_path,
            "-filter_complex",
                "[0:v]scale=1920:1080:force_original_aspect_ratio=decrease,"
                "pad=1920:1080:(ow-iw)/2:(oh-ih)/2:color=black,"
                "format=yuv420p[final]",
            "-map", "[final]", "-map", "1:a",
            "-c:v", "libx264", "-preset", "fast",
            "-c:a", "aac", "-b:a", "192k",
            "-shortest", output_path
        ]
    
    try:
        result = subprocess.run(command, check=True, capture_output=True)
        size = os.path.getsize(output_path) / 1024 / 1024
        print(f"  [MERGE] Scene merged: {size:.1f} MB")
        return True
    except subprocess.CalledProcessError as e:
        print(f"  [MERGE] FAILED: {e.stderr.decode()[:400]}")
        return False


# ===========================================================
# MAIN WORKER LOOP
# ===========================================================

def run_worker(drive_path, comfyui_output_dir, max_scenes=None):
    """
    Main worker loop. Runs until no more scenes are available.
    
    Args:
        drive_path: Path to AnimeFactory on mounted Google Drive
        comfyui_output_dir: ComfyUI's local output directory
        max_scenes: Optional limit on scenes to process this session
    """
    worker_id = f"worker_{uuid.uuid4().hex[:8]}"
    state = DriveState(drive_path)
    
    print(f"\n{'='*60}")
    print(f"  DISTRIBUTED WORKER: {worker_id}")
    print(f"  Drive: {drive_path}")
    print(f"  ComfyUI: {COMFYUI_URL}")
    print(f"{'='*60}\n")
    
    # Wait for ComfyUI
    if not wait_for_comfyui_ready():
        return
    
    # Clean up any leftovers from crashed workers
    state.cleanup_stale()
    state.get_summary()
    
    scenes_processed = 0
    
    while True:
        # Check scene limit
        if max_scenes and scenes_processed >= max_scenes:
            print(f"\n[WORKER] Reached limit of {max_scenes} scenes. Stopping.")
            break
        
        # Claim next scene
        scene_info = state.claim_next_scene(worker_id)
        if not scene_info:
            print("\n[WORKER] No more scenes to process. Worker complete!")
            break
        
        scene_id = scene_info["id"]
        print(f"\n{'='*50}")
        print(f"  Processing: {scene_id}")
        print(f"  Type: {scene_info['data'].get('type', 'image')}")
        print(f"  Text: {scene_info['data'].get('text', '')[:80]}...")
        print(f"{'='*50}")
        
        try:
            # Process the scene
            tmp_output = process_scene(scene_info, state, comfyui_output_dir)
            
            if tmp_output and os.path.exists(tmp_output):
                # Success! Atomic write to Drive
                state.complete_scene(scene_id, tmp_output)
                scenes_processed += 1
            else:
                # Generation failed — release scene for retry
                state.fail_scene(scene_id)
        
        except KeyboardInterrupt:
            print(f"\n[WORKER] Interrupted! Releasing {scene_id}...")
            state.fail_scene(scene_id)
            break
        
        except Exception as e:
            print(f"\n[WORKER] Unexpected error on {scene_id}: {e}")
            state.fail_scene(scene_id)
            # Continue to next scene instead of crashing
            continue
    
    # Final summary
    state.get_summary()
    print(f"\n[WORKER] {worker_id} processed {scenes_processed} scenes. Goodbye!")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Distributed Scene Worker")
    parser.add_argument("--drive-path", type=str, required=True,
                        help="Path to AnimeFactory on mounted Drive")
    parser.add_argument("--comfyui-output", type=str, 
                        default="/content/ComfyUI/output",
                        help="ComfyUI's local output directory")
    parser.add_argument("--max-scenes", type=int, default=None,
                        help="Max scenes to process (optional)")
    
    args = parser.parse_args()
    run_worker(args.drive_path, args.comfyui_output, args.max_scenes)
